export default [
  {path: '/user', layout: false, routes: [{path: '/user/login', component: './User/Login'}]},
  {path: '/user', layout: false, routes: [{path: '/user/register', component: './User/Register'}]},
  {path: '/', redirect: '/add_chart'},
  {path: '/add_chart', name: '智能分析', icon: 'barChart', component: './AddChart'},
  {path: '/add_chart_async', name: '智能分析（异步）', icon: 'barChart', component: './AddChartAsync'},
  {path: '/team', name: '队伍大厅', icon: 'TeamOutlined', component: './Team'},
  {path: '/team_my_joined', name: '已加队伍', icon: 'TeamOutlined', component: './TeamMyJoined'},
  {path: '/my_chart', name: '我的图表', icon: 'pieChart', component: './MyChart'},
  {path: '/team/:id/chart', hideInMenu: true, name: '队伍图表', icon: 'pieChart', component: './TeamChart'},
  {
    path: '/admin',
    name: '管理页',
    icon: 'crown',
    access: 'canAdmin',
    routes: [
      {path: '/admin/user-manage', name: '用户管理', icon: 'smile', component: './Admin/UserManage'},
      {path: '/admin/chart-manage', name: '图表管理', icon: 'barChart', component: './Admin/chartManage'},
      {path: '/admin/team', name: '队伍管理', icon: 'TeamOutlined', component: './Admin/TeamManage'},
      {component: './404'},
    ],
  },
  {path: '/', redirect: '/welcome'},
  {path: '*', layout: false, component: './404'},
  {
    path: '/user/center',
    name: '个人中心',
    icon: 'smile',
    component: './UserCenter',
  },
];
